package com.codecrafthub.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * A course a developer wants to learn.
 *
 * This is a "plain old Java object" (POJO). Jackson (Spring Boot's default
 * JSON library) uses the getters/setters below to convert this object to
 * and from JSON automatically - we never write JSON parsing code by hand.
 *
 * Field name mapping (Java -> JSON):
 *   id          -> id           (server-generated, starts at 1)
 *   name        -> name
 *   description -> description
 *   targetDate  -> target_date  (via @JsonProperty, format yyyy-MM-dd)
 *   status      -> status       (must be "Not Started", "In Progress" or "Completed")
 *   createdAt   -> created_at   (server-generated timestamp, via @JsonProperty)
 */
public class Course {

    // Auto-generated by CourseService (starting at 1). Clients never send this.
    private Integer id;

    @NotBlank(message = "name is required")
    private String name;

    @NotBlank(message = "description is required")
    private String description;

    // "@JsonProperty" tells Jackson to read/write this field as "target_date"
    // in JSON, even though the Java field is named "targetDate" (camelCase,
    // the normal Java naming convention).
    @NotNull(message = "target_date is required (format: yyyy-MM-dd)")
    @JsonProperty("target_date")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private LocalDate targetDate;

    // Kept as a plain String rather than a Java enum so CourseService can
    // return a friendly, custom error message when the value isn't exactly
    // "Not Started", "In Progress" or "Completed" (see CourseService.VALID_STATUSES).
    @NotBlank(message = "status is required")
    private String status;

    // Auto-generated the moment the course is created. Clients never send this;
    // it is only ever present in responses.
    @JsonProperty("created_at")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime createdAt;

    public Course() {
    }

    public Course(Integer id, String name, String description, LocalDate targetDate,
                  String status, LocalDateTime createdAt) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.targetDate = targetDate;
        this.status = status;
        this.createdAt = createdAt;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getTargetDate() {
        return targetDate;
    }

    public void setTargetDate(LocalDate targetDate) {
        this.targetDate = targetDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
